# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PR_BRANCH: concatMD-${{ github.run_number }}

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Merge

      - name: make PR_BRANCH
        if: ${{ success() }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git checkout -b ${{ env.PR_BRANCH }} origin/concatMD
          git push origin ${{ env.PR_BRANCH }}
          git checkout ${{ github.ref }}

      # Concat files        
      - name: Concat document
        run: cat 01_*.md 02_*.md 03_*.md > README.md
        
      - name: pull request
        if: ${{ success() }}
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update markdown
          committer: GitHub <noreply@github.com>
          author: ${{ github.actor }} <${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: ${{ env.PR_BRANCH }}
          base: concatMD
          delete-branch: true
          title: 'Update markdown'
          body: |
            Update report
          labels: |
            automated pr
          draft: false
